# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Delta_calc_cpp <- function(mm, mmlag, gammamat, tol, maxit, trace) {
    .Call('_OMTM1_Delta_calc_cpp', PACKAGE = 'OMTM1', mm, mmlag, gammamat, tol, maxit, trace)
}

Delta_calcWith0TxProbs_cpp <- function(mm, mmlag, gammamat, CalcTxMtx, tol, maxit, trace) {
    .Call('_OMTM1_Delta_calcWith0TxProbs_cpp', PACKAGE = 'OMTM1', mm, mmlag, gammamat, CalcTxMtx, tol, maxit, trace)
}

delta_it_cpp <- function(mm, mmlag, gammamat, tol, maxit, trace) {
    .Call('_OMTM1_delta_it_cpp', PACKAGE = 'OMTM1', mm, mmlag, gammamat, tol, maxit, trace)
}

dfdDelta_calc_cpp <- function(mmlag, hmat) {
    .Call('_OMTM1_dfdDelta_calc_cpp', PACKAGE = 'OMTM1', mmlag, hmat)
}

dhd_gamma_calc <- function(hmat, mm_lag, tmp_mat) {
    .Call('_OMTM1_dhd_gamma_calc', PACKAGE = 'OMTM1', hmat, mm_lag, tmp_mat)
}

dhdgamma_mmlag_calc_cpp <- function(hmat1, mmlag1) {
    .Call('_OMTM1_dhdgamma_mmlag_calc_cpp', PACKAGE = 'OMTM1', hmat1, mmlag1)
}

dmumdtheta_calc_cpp <- function(dpidtheta) {
    .Call('_OMTM1_dmumdtheta_calc_cpp', PACKAGE = 'OMTM1', dpidtheta)
}

dpidtheta_calc_cpp <- function(detadtheta, dpideta) {
    .Call('_OMTM1_dpidtheta_calc_cpp', PACKAGE = 'OMTM1', detadtheta, dpideta)
}

dpidtheta_calc1_cpp <- function(diagmtx, dpideta, xit) {
    .Call('_OMTM1_dpidtheta_calc1_cpp', PACKAGE = 'OMTM1', diagmtx, dpideta, xit)
}

dpidtheta_calc2_cpp <- function(diagmtx, dpideta, xit, ppoMat) {
    .Call('_OMTM1_dpidtheta_calc2_cpp', PACKAGE = 'OMTM1', diagmtx, dpideta, xit, ppoMat)
}

hmat_calc_cpp <- function(Deltavec, gammamat) {
    .Call('_OMTM1_hmat_calc_cpp', PACKAGE = 'OMTM1', Deltavec, gammamat)
}

loglikelihood <- function() {
    .Call('_OMTM1_loglikelihood', PACKAGE = 'OMTM1')
}

